config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "briefs#new"
  resources :briefs
  get "/pages/:page" => "pages#show"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new(role: "user_role") # not logged in
    case user.role
    when "user_role"
      can :create, Brief
    else
      "admin_role"
      can :manage, :all

    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brief.rb
class Brief < ApplicationRecord
  validates :user_id, presence: true

  belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable, :recoverable, :validatable

  has_many :briefs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception
end

app/controllers/briefs_controller.rb
class BriefsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_brief, only: %w[show, create, destroy]

  # GET /briefs
  # GET /briefs.json
  def index
    @briefs = Brief.all
  end

  # GET /briefs/1
  # GET /briefs/1.json
  def show
    @brief = Brief.find(params[:id])
  end

  # GET /briefs/new
  def new
    @brief = Brief.new
  end

  # GET /briefs/1/edit
  def edit;
  end

  # POST /briefs
  # POST /briefs.json
  def create
    @brief = current_user.briefs.build(brief_params)

    respond_to do |format|
      if @brief.save
        format.html { render template: "pages/client-show" }
        format.json { render template: "pages/#{params[:page]}" }
      else
        format.html { render :new }
        format.json { render json: @brief.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /briefs/1
  # PATCH/PUT /briefs/1.json
  def update
    respond_to do |format|
      if @brief.update(brief_params)
        format.html { redirect_to @brief, notice: 'Brief was successfully updated.' }
        format.json { render :show, status: :ok, location: @brief }
      else
        format.html { render :edit }
        format.json { render json: @brief.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /briefs/1
  # DELETE /briefs/1.json
  def destroy
    @brief.destroy
    respond_to do |format|
      format.html { redirect_to @brief, notice: 'Brief was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_brief
    @brief = Brief.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def brief_params
    params.require(:brief).permit(:company, :brand, :description, :email, :contact,
                                  :offers, :competition, :project, :structure, :group, :budget, :daadline,
                                  :example, :featured, :additional, :architecture, :language, :design, :color)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    if valid_page?
      render template: "pages/#{params[:page]}"
    else
      render file: "public/404.html", status: :not_found
    end
  end

  private

  def valid_page?
    File.exist?(Pathname.new(Rails.root + "app/views/pages/#{params[:page]}.html.erb"))
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/briefs_helper.rb
module BriefsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/briefs/_form.html.erb
<div class="uk-container uk-margin">
  <%= form_with(model: brief, local: true) do |form| %>
    <% if brief.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(brief.errors.count, "error") %> prohibited this brief from being saved:</h2>

        <ul>
          <% brief.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <form>
      <fieldset class="uk-fieldset uk-margin-medium-top uk-width-1-1 uk-width-1-2@m">
        <legend class="uk-legend">Brief dotyczący projektu strony www</legend>
        <p class="uk-text-justify uk-margin-large-bottom">Brief pozwoli nam poznać oczekiwania odnośnie projektu.
          Wszystkie
          informacje w nim zawarte objęte są klauzulą
          poufności i zostaną wykorzystane jedynie na potrzeby przygotowania oferty i projektu. Jeżeli niektóre pytania
          wydają się zbędne można je pominąć. W razie pytań czy wątpliwości jesteśmy do dyspozycji.</p>

        <div class="uk-margin">
          <p>Nazwa firmy</p>
          <%= form.text_field :company, class: "uk-input", type: "text" %>
        </div>

        <div class="uk-margin">
          <p>Branża</p>
          <%= form.text_field :brand, class: "uk-input", type: "text" %>
        </div>

        <div class="uk-margin">
          <p>Opis firmy</p>
          <%= form.text_area :description, class: "uk-textarea", type: "text-area", rows: "5" %>
        </div>

        <div class="uk-margin">
          <p>E-Mail</p>
          <%= form.text_field :email, class: "uk-input", type: "text" %>
        </div>

        <div class="uk-margin">
          <p>Osoba kontaktowa + numer telefonu</p>
          <%= form.text_field :contact, class: "uk-input", type: "text" %>
        </div>

        <div class="uk-margin">
          <p>Oferowane usługi/produkty</p>
          <%= form.text_area :offers, class: "uk-textarea", type: "text-area", rows: "3" %>
        </div>

        <div class="uk-margin">
          <p>Opis rynku i środowiska konkurencji</p>
          <%= form.text_area :competition, class: "uk-textarea", type: "text-area", rows: "5" %>
        </div>

        <div class="uk-margin">
          <p>Informacje o projekcie strony www / aplikacji</p>
          <%= form.text_area :project, class: "uk-textarea", type: "text-area", rows: "5" %>
        </div>

        <div class="uk-margin">
          <p>Jaką architekturę informacji powinien mieć projekt?</p>
          <%= form.select(:architecture, [["wybierz", 0], ["Wizerunkowy, np. wizytówka firmy, strona korporacyjna", 1], ["Sprzedażowy,
          np. strona e-commerce", 2], ["Informacyjny, np. portal, serwis", 3], ["Landing page, np. promocja produktu,
          usługi", 4], ["Interfejs aplikacji", 5]], class: "uk-select") %>
        </div>

        <div class="uk-margin">
          <p>Ułożenie elementów na stronie, czyli przewidywana struktura projektu</p>
          <%= form.text_area :structure, class: "uk-textarea", type: "text-area", rows: "5" %>
        </div>

        <div class="uk-margin">
          <p>Jaka jest grupa docelowa?</p>
          <%= form.text_field :group, class: "uk-input", type: "text" %>
        </div>

        <div class="uk-margin">
          <p>Przewidywany budżet projektu</p>
          <%= form.text_area :budget, class: "uk-textarea", type: "text-area", rows: "3" %>
        </div>

        <div class="uk-margin">
          <p>Oczekiwania dotyczące terminu realizacji</p>
          <%= form.date_select :daadline, class: "uk-select" %>
        </div>

        <div class="uk-margin">
          <p>Czy strona ma być wielojęzyczna?</p>
          <%= form.select(:language, [["Tak", true], ["Nie", false]], class: "uk-select") %>
        </div>

        <div class="uk-margin">
          <p>Oczekiwana stylistyka projektu:</p>
          <%= form.select(:design, [["wybierz", 0], ["Minimalistyczna", 1], ["Duża ilość grafiki", 2], ["Poważna/Stonowana", 3],
                                    ["Zabawna/Wesoła", 4], ["Prosta", 5], ["Elegancka", 6]], class: "uk-select") %>
        </div>

        <div class="uk-margin">
          <p>Oczekiwana stylistyka projektu</p>
          <%= form.select(:color, [["wybierz", 0], ["Jasny", 1], ["Ciemny", 2], ["Kolory firmowe", 3],
                                   ["Jaskrawe", 4], ["Czarno-białe", 5], ["Pastele", 6]], class: "uk-select") %>
        </div>

        <div class="uk-margin">
          <p>Przykłady stron, które odpowiadają Państwa oczekiwaniom wizualnym</p>
          <%= form.text_area :example, class: "uk-textarea", type: "text-area", rows: "3" %>
        </div>

        <div class="uk-margin">
          <p>Jakie elementy/informacje powinny zostać wyróżnione w projekcie?</p>
          <%= form.text_area :featured, class: "uk-textarea", type: "text-area", rows: "3" %>
        </div>

        <div class="uk-margin">
          <p>Dodatkowe informacje</p>
          <%= form.text_area :additional, class: "uk-textarea", type: "text-area", rows: "3" %>
        </div>

        <div class="uk-margin">
          <%= form.submit class: "uk-button uk-button-primary" %>
        </div>
      </fieldset>
    </form>
  <% end %>
</div>

app/views/briefs/edit.html.erb
<h1>Editing Brief</h1>

<%= render 'form', brief: @brief %>

<%= link_to 'Show', @brief %> |
<%= link_to 'Back', briefs_path %>

app/views/briefs/index.html.erb
<div class="uk-container uk-margin">
  <div class="uk-flex uk-flex-column uk-flex-center">
    <h1>Lista briefów od klientów</h1>
    <div class="uk-overflow-auto">
      <table class="uk-table uk-table-striped">
        <thead>
        <tr>
          <th class="uk-table-expand">Nazwa firmy</th>
          <th class="uk-table-expand">Branża</th>
          <th class="uk-table-expand">Opis firmy</th>
          <th class="uk-table-shrink uk-text-nowrap">E-mail</th>
          <th class="uk-table-expand">Osoba kontaktowa</th>
          <th class="uk-table-expand uk-text-nowrap">Oferowane usługi/produkty</th>
          <th class="uk-table-expand uk-text-nowrap">Opis rynku i środowiska konkurencji</th>
          <th class="uk-table-expand uk-text-nowrap">Informacje o projekcie strony www / aplikacji</th>
          <th class="uk-table-expand uk-text-nowrap">Jaką architekturę informacji powinien mieć projekt?</th>
          <th class="uk-table-expand uk-text-nowrap">Ułożenie elementów na stronie, czyli przewidywana struktura
            projektu
          </th>
          <th class="uk-table-shrink">Jaka jest grupa docelowa?</th>
          <th class="uk-table-shrink">Przewidywany budżet projektu</th>
          <th class="uk-table-shrink">Czy strona ma być wielojęzyczna?</th>
          <th class="uk-table-shrink uk-text-nowrap">Oczekiwania dotyczące terminu realizacji</th>
          <th class="uk-table-shrink uk-text-nowrap">Oczekiwana stylistyka projektu</th>
          <th class="uk-table-shrink uk-text-nowrap">Kolorystyka projektu</th>
          <th class="uk-table-expand uk-text-nowrap">Przykłady stron, które odpowiadają Państwa oczekiwaniom wizualnym
          </th>
          <th class="uk-table-shrink uk-text-nowrap">Jakie elementy/informacje powinny zostać wyróżnione w projekcie?
          </th>
          <th class="uk-table-shrink uk-text-nowrap">Dodatkowe informacje</th>
          <th colspan="2"></th>
        </tr>
        </thead>

        <tbody>
        <% @briefs.each do |brief| %>
          <tr>
            <td><%= brief.company %></td>
            <td><%= brief.brand %></td>
            <td class="uk-text-truncate"><%= brief.description %></td>
            <td><%= brief.email %></td>
            <td><%= brief.contact %></td>
            <td><%= brief.offers %></td>
            <td><%= brief.competition %></td>
            <td><%= brief.project %></td>
            <td><%= brief.structure %></td>
            <td><%= brief.architecture %></td>
            <td><%= brief.group %></td>
            <td><%= brief.budget %></td>
            <td><%= brief.language %></td>
            <td><%= brief.daadline %></td>
            <td><%= brief.design %></td>
            <td><%= brief.color %></td>
            <td><%= brief.example %></td>
            <td><%= brief.featured %></td>
            <td><%= brief.additional %></td>
            <td><%= link_to 'Pokaż', brief, class: "uk-button uk-button-default", type: "button" %></td>
            <td><%= link_to "Usuń", brief, method: :delete, class: "uk-button uk-button-default", type: "button" %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>

    <br>

  </div>
  <%= link_to 'New Brief', new_brief_path, class: "uk-button uk-button-primary", type: "button" %>
</div>

app/views/briefs/new.html.erb
<div class="uk-container uk-margin">
  <div class="logo uk-visible@l">
    <%= image_tag("logo.png") %>
  </div>
  <div class="uk-container uk-margin">
    <div class="logo-second uk-hidden@l">
      <%= image_tag("logo.png") %>
    </div>
  </div>

  <%= render 'form', brief: @brief %>
</div>

app/views/briefs/show.html.erb
<p>
  <strong>Company:</strong>
  <%= @brief.company %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @brief.brand %>
</p>

<p>
  <strong>Description:</strong>
  <%= @brief.description %>
</p>

<p>
  <strong>Email:</strong>
  <%= @brief.email %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @brief.contact %>
</p>

<p>
  <strong>Offers:</strong>
  <%= @brief.offers %>
</p>

<p>
  <strong>Competition:</strong>
  <%= @brief.competition %>
</p>

<p>
  <strong>Project:</strong>
  <%= @brief.project %>
</p>

<p>
  <strong>Structure:</strong>
  <%= @brief.structure %>
</p>

<p>
  <strong>Architecture:</strong>
  <%= @brief.architecture %>
</p>

<p>
  <strong>Group:</strong>
  <%= @brief.group %>
</p>

<p>
  <strong>Budget:</strong>
  <%= @brief.budget %>
</p>

<p>
  <strong>Daadline:</strong>
  <%= @brief.daadline %>
</p>

<p>
  <strong>Example:</strong>
  <%= @brief.example %>
</p>

<p>
  <strong>Featured:</strong>
  <%= @brief.featured %>
</p>

<p>
  <strong>Additional:</strong>
  <%= @brief.additional %>
</p>

<%= link_to 'Edit', edit_brief_path(@brief) %> |
<%= link_to 'Back', briefs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pl">
<head>
  <title>Brief Devrry</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application.scss', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-rc.15/css/uikit.min.css">
</head>
<body>

  <%= yield %>

<!-- JS -->
<script src="//cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-rc.15/js/uikit.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-rc.15/js/uikit-icons.min.js"></script>
</body>
</html>

app/views/pages/client-show.html.erb
<div class="client-show">
  <div class="uk-flex uk-flex-center">
    <div class="uk-card uk-card-default uk-card-body uk-width-1-2@m uk-margin-xlarge-top uk-flex-middle">
      <div class="uk-text-center">
        <h1>Dziękujemy za przesłanie briefa!</h1>
        <h2>Odpowiemy na niego w ciągu 24h</h2>
        <h3>Zapraszamy<a href="//devrry.com"> www.devrry.com</a></h3></div>
    </div>
  </div>
</div>